[package]
name = "rpm-rs"
version = "0.8.1"
authors = [
    "René Richter <richterrettich@gmail.com>",
    "Bernhard Schuster <bernhard@ahoi.io>"
]
edition = "2018"
license = "Apache-2.0"
description = "A pure rust library for building and parsing RPM's"
homepage = "https://github.com/Richterrettich/rpm-rs"
repository = "https://github.com/Richterrettich/rpm-rs"
readme = "README.md"
keywords = ["RPM", "packaging"]
categories = ["parsing", "development-tools"]

[lib]
name = "rpm"

[dependencies]
tokio = {version = "1.11", features = ["fs", "io-util"]}
thiserror = "1"
nom = "7"
num-traits = "0.2"
num-derive = "0.3"
num = "0.4"
enum-primitive-derive = "0.2"
enum-display-derive = "0.1"
cpio = "0.2"
# consider migrating to flate2
libflate = "1"
sha2 = "0.10"
md-5 = "0.10"
sha1 = "0.10"
rand = { version = "0.8" }
pgp = { version="0.7.2", optional = true }
chrono = "0.4"
log = "0.4"
itertools = "0.10"
hex = { version = "0.4", features = ["std"] }
zstd = "0.9.0"

[dev-dependencies]
rsa = { version = "0.5" }
rsa-der = { version = "^0.2.1" }
env_logger = "0.9"
serial_test = "0.5"
tokio = {version = "1", features = ["full"]}


[features]
default = ["signature-pgp","async-tokio"]

signature-pgp = ["signature-meta", "pgp"]
signature-meta = []
test-with-podman = ["signature-meta"]
async-tokio = []
